services:
  nginx:
    image: nginx:1.29
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Active config is ./nginx.conf (we'll start with HTTP-only, then switch to HTTPS)
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Your static site
      - ./:/usr/share/nginx/html:ro
      # ACME challenge webroot
      - ./certbot-www:/var/www/certbot:rw
      # Persisted certs/keys
      - ./letsencrypt:/etc/letsencrypt:rw

  # One-shot cert / renew runs (invoked with `docker compose run --rm certbot ...`)
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot-www:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt
